### ISSUE TITLE
Please rebuild v8-r

### ISSUE THREAD

**Issue by leofontenelle** [JanMarvin/archpkgs#1]
Currently the /usr/lib/libv8.so is linked to libicui18n.so.68, but current version in Arch is icu 69. Thanks in advance!

**Comment by JanMarvin** [comment]
will do, thanks for the report.

**Comment by JanMarvin** [comment]
fixed in https://github.com/JanMarvin/archpkgs/commit/0471cd18975563bc97a3ffe750aaac6b6679f45f

Will update v8 again soon, now that V8 3.4.1 is on CRAN.
